import type {
	Activity,
	Badge,
	Comment,
	Entry,
	HelpContribution,
	Post,
	User,
	UserRank,
	Reply,
	Wallet,
	Burn,
	Like,
	Share,
} from "./types";
import { PostStatus, PostCategory, SelectionMethod, BadgeTier } from "./types";

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 24 * 60 * 60 * 1000);
const hoursAgo = (hours: number) => new Date(now - hours * 60 * 60 * 1000);
const daysFromNow = (days: number) =>
	new Date(now + days * 24 * 60 * 60 * 1000);

export const userRanks: UserRank[] = [
	{ level: 1, title: "Newcomer", color: "text-gray-500", minPoints: 0 },
	{ level: 2, title: "Helper", color: "text-green-500", minPoints: 100 },
	{ level: 3, title: "Contributor", color: "text-blue-500", minPoints: 500 },
	{ level: 4, title: "Champion", color: "text-orange-500", minPoints: 1000 },
	{ level: 5, title: "Legend", color: "text-orange-500", minPoints: 2500 },
];

// Mock badges covering all tiers.
export const badges: Badge[] = [
	{
		id: "badge-bronze",
		name: "Helper",
		description: "Awarded for making your first contribution",
		tier: BadgeTier.Bronze,
		icon: "🥉",
		color: "bg-orange-100 text-orange-800",
		xpReward: 10,
		criteria: "1+ contributions",
	},
	{
		id: "badge-silver",
		name: "Contributor",
		description: "Awarded for making 5 contributions",
		tier: BadgeTier.Silver,
		icon: "🥈",
		color: "bg-slate-100 text-slate-800",
		xpReward: 50,
		criteria: "5+ contributions",
	},
	{
		id: "badge-gold",
		name: "Community Pillar",
		description: "Awarded for making 10 contributions",
		tier: BadgeTier.Gold,
		icon: "🥇",
		color: "bg-yellow-100 text-yellow-800",
		xpReward: 100,
		criteria: "10+ contributions",
	},
	{
		id: "badge-platinum",
		name: "Legend",
		description: "Awarded for making 25 contributions",
		tier: BadgeTier.Platinum,
		icon: "💎",
		color: "bg-indigo-100 text-indigo-800",
		xpReward: 250,
		criteria: "25+ contributions",
	},
	{
		id: "badge-diamond",
		name: "Icon",
		description: "Awarded for making 50 contributions",
		tier: BadgeTier.Diamond,
		icon: "👑",
		color: "bg-purple-100 text-purple-800",
		xpReward: 500,
		criteria: "50+ contributions",
	},
];

// Mock wallets for development and testing.
export const mockWallets: Wallet[] = [
	{
		publicKey: "GAS4Q3L3R6J2H7B7W4VJ4M7K7P6C4LQ5L3J6M7N8P9",
		balance: 2500.75,
		currency: "USDC",
	},
	{
		publicKey: "GB2J8K3P9N7M6L4C2V5B7N8M1K2J9H8G7F6D5S4",
		balance: 890.25,
		currency: "USDC",
	},
	{
		publicKey: "GDR8F4H2J6K7L9M3N5B8V1C2X3Z5A6S7D8F9G1",
		balance: 5200.0,
		currency: "USDC",
	},
	{
		publicKey: "GC9D2S5A7F1G3H6J8K2L4M9N7B5V3C1X8Z6Q4",
		balance: 125.5,
		currency: "USDC",
	},
	{
		publicKey: "GJ7K4L2M8N6B5V3C1X9Z7Q5W2E4R6T8Y1U3",
		balance: 1750.8,
		currency: "USDC",
	},
	{
		publicKey: "GA6S3D9F5G1H7J2K4L8M6N9B5V3C1X7Z4Q2",
		balance: 450.0,
		currency: "USDC",
	},
	{
		publicKey: "GF5D8S2A6F4G7H1J9K3L6M2N8B5V9C1X4Z7",
		balance: 3200.5,
		currency: "USDC",
	},
	{
		publicKey: "GH6J3K9L2M8N4B5V7C1X3Z5Q6W8E2R4T7Y1",
		balance: 1680.25,
		currency: "USDC",
	},
	{
		publicKey: "GK2L7M4N9B6V1C3X5Z8Q2W4E7R9T1Y3U6",
		balance: 280.75,
		currency: "USDC",
	},
	{
		publicKey: "GN3M8B2V5C7X1Z4Q6W9E2R5T8Y1U3I6O4",
		balance: 920.4,
		currency: "USDC",
	},
];

// Mock users: add new users with unique IDs and matching wallet info.
export const mockUsers: User[] = [
	{
		id: "1",
		publicKey: mockWallets[0].publicKey,
		name: "Alex Chen",
		username: "alexchen",
		email: "alex@example.com",
		avatar: "/professional-asian-person.png",
		bio: "Crypto enthusiast and community builder. Love helping others succeed! 🚀",
		walletAddress: "0x1234...5678",
		walletBalance: mockWallets[0].balance,
		followersCount: 1250,
		followingCount: 340,
		postsCount: 45,
		rank: userRanks[3],
		badges: [badges[0], badges[1], badges[2], badges[3]],
		joinedAt: daysAgo(210),
		isVerified: true,
	},
	{
		id: "2",
		publicKey: mockWallets[1].publicKey,
		name: "Sarah Johnson",
		username: "sarahj",
		email: "sarah@example.com",
		avatar: "/friendly-woman-smiling.png",
		bio: "Artist and designer. Creating beautiful things and spreading positivity ✨",
		walletAddress: "0x2345...6789",
		walletBalance: mockWallets[1].balance,
		followersCount: 850,
		followingCount: 200,
		postsCount: 32,
		rank: userRanks[2],
		badges: [badges[0], badges[1], badges[2]],
		joinedAt: daysAgo(180),
		isVerified: false,
	},
	{
		id: "3",
		publicKey: mockWallets[2].publicKey,
		name: "Marcus Williams",
		username: "marcusw",
		email: "marcus@example.com",
		avatar: "/confident-black-man.png",
		bio: "Tech entrepreneur. Building the future one project at a time 💻",
		walletAddress: "0x3456...7890",
		walletBalance: mockWallets[2].balance,
		followersCount: 2100,
		followingCount: 150,
		postsCount: 67,
		rank: userRanks[4],
		badges: badges,
		joinedAt: daysAgo(260),
		isVerified: true,
	},
	{
		id: "4",
		publicKey: mockWallets[3].publicKey,
		name: "Emma Rodriguez",
		username: "emmar",
		email: "emma@example.com",
		avatar: "/young-latina-woman.png",
		bio: "Student and aspiring developer. Always learning something new! 📚",
		walletAddress: "0x4567...8901",
		walletBalance: mockWallets[3].balance,
		followersCount: 320,
		followingCount: 450,
		postsCount: 18,
		rank: userRanks[1],
		badges: [badges[0]],
		joinedAt: daysAgo(40),
		isVerified: false,
	},
	{
		id: "5",
		publicKey: mockWallets[4].publicKey,
		name: "David Kim",
		username: "davidk",
		email: "david@example.com",
		avatar: "/korean-man-glasses.png",
		bio: "Gaming content creator and streamer. Let's play together! 🎮",
		walletAddress: "0x5678...9012",
		walletBalance: mockWallets[4].balance,
		followersCount: 980,
		followingCount: 280,
		postsCount: 41,
		rank: userRanks[2],
		badges: [badges[0], badges[1]],
		joinedAt: daysAgo(150),
		isVerified: true,
	},
	{
		id: "6",
		publicKey: mockWallets[5].publicKey,
		name: "Chioma Okafor",
		username: "chiokafor",
		email: "chioma@example.com",
		avatar: "/placeholder-user.jpg",
		bio: "University of Port Harcourt student. Studying Computer Science and building the future 💻",
		walletAddress: "0x6789...0123",
		walletBalance: mockWallets[5].balance,
		followersCount: 420,
		followingCount: 180,
		postsCount: 22,
		rank: userRanks[2],
		badges: [badges[0], badges[1]],
		joinedAt: daysAgo(120),
		isVerified: false,
	},
	{
		id: "7",
		publicKey: mockWallets[6].publicKey,
		name: "Tunde Bakare",
		username: "tbakare",
		email: "tunde@example.com",
		avatar: "/placeholder-user.jpg",
		bio: "Small business owner in Lagos. Love giving back to my community 🙌",
		walletAddress: "0x7890...1234",
		walletBalance: mockWallets[6].balance,
		followersCount: 1580,
		followingCount: 95,
		postsCount: 53,
		rank: userRanks[3],
		badges: [badges[0], badges[1], badges[2]],
		joinedAt: daysAgo(230),
		isVerified: true,
	},
	{
		id: "8",
		publicKey: mockWallets[7].publicKey,
		name: "Adaeze Nwosu",
		username: "adaeze",
		email: "adaeze@example.com",
		avatar: "/placeholder-user.jpg",
		bio: "Fashion designer and entrepreneur. Helping others chase their dreams ✨",
		walletAddress: "0x8901...2345",
		walletBalance: mockWallets[7].balance,
		followersCount: 920,
		followingCount: 310,
		postsCount: 38,
		rank: userRanks[2],
		badges: [badges[0], badges[1]],
		joinedAt: daysAgo(170),
		isVerified: true,
	},
	{
		id: "9",
		publicKey: mockWallets[8].publicKey,
		name: "Kunle Adeyemi",
		username: "kunle_a",
		email: "kunle@example.com",
		avatar: "/placeholder-user.jpg",
		bio: "Final year Engineering student at UNILAG. Love tech and helping people 🚀",
		walletAddress: "0x9012...3456",
		walletBalance: mockWallets[8].balance,
		followersCount: 380,
		followingCount: 420,
		postsCount: 15,
		rank: userRanks[1],
		badges: [badges[0]],
		joinedAt: daysAgo(35),
		isVerified: false,
	},
	{
		id: "10",
		publicKey: mockWallets[9].publicKey,
		name: "Blessing Eze",
		username: "blessing_e",
		email: "blessing@example.com",
		avatar: "/placeholder-user.jpg",
		bio: "Content creator and community advocate. Spreading love and positivity 💚",
		walletAddress: "0xA012...7890",
		walletBalance: mockWallets[9].balance,
		followersCount: 1150,
		followingCount: 225,
		postsCount: 44,
		rank: userRanks[3],
		badges: [badges[0], badges[1], badges[2], badges[3], badges[4]],
		joinedAt: daysAgo(200),
		isVerified: true,
	},
];

// Mock entries: add new entries with a valid postId and userId.
export const mockEntries: Entry[] = [
	{
		id: "1",
		postId: "1",
		userId: "2",
		user: mockUsers[1],
		message:
			"Started coding 2 years ago with Python! Currently building a web app for local businesses. @davidk @emmar check this out!",
		submittedAt: daysAgo(20),
		proofUrl: "https://github.com/sarahj/local-business-app",
	},
	{
		id: "2",
		postId: "1",
		userId: "5",
		user: mockUsers[4],
		message:
			"Been coding for 3 years, started with game development! Now working on streaming tools. @emmar @sarahj",
		submittedAt: daysAgo(20),
		proofUrl: "https://github.com/davidk/stream-tools",
	},
	{
		id: "7",
		postId: "1",
		userId: "4",
		user: mockUsers[3],
		message:
			"That's so cool @sarahj! I'm also learning web development. Would love to collaborate sometime!",
		submittedAt: daysAgo(20),
		parentId: "1",
	},
	{
		id: "8",
		postId: "1",
		userId: "1",
		user: mockUsers[0],
		message:
			"@davidk Your streaming tools look amazing! Have you considered open sourcing them?",
		submittedAt: daysAgo(19),
		parentId: "2",
	},
	{
		id: "9",
		postId: "1",
		userId: "2",
		user: mockUsers[1],
		message: "@emmar DM me and we can set up a call to discuss ideas 😊",
		submittedAt: daysAgo(19),
		parentId: "7",
	},
	{
		id: "13",
		postId: "1",
		userId: "5",
		user: mockUsers[4],
		message:
			"@alexchen Thanks! We're actually planning to open source it next quarter 🎉",
		submittedAt: daysAgo(19),
		parentId: "8",
	},
	{
		id: "14",
		postId: "1",
		userId: "1",
		user: mockUsers[0],
		message: "@davidk That's amazing! Can't wait to contribute 💪",
		submittedAt: daysAgo(19),
		parentId: "13",
	},
	{
		id: "15",
		postId: "1",
		userId: "4",
		user: mockUsers[3],
		message: "@sarahj Awesome! I'll definitely reach out, thanks so much! 🙌",
		submittedAt: daysAgo(19),
		parentId: "9",
	},
	{
		id: "3",
		postId: "3",
		userId: "4",
		user: mockUsers[3],
		message:
			"Here's my latest digital art piece! Been working on this cyberpunk series.",
		submittedAt: daysAgo(22),
		proofUrl: "https://artstation.com/emmar/cyberpunk-series",
	},
	{
		id: "10",
		postId: "3",
		userId: "2",
		user: mockUsers[1],
		message:
			"@emmar This is incredible! The color palette is perfect. How long did this take you?",
		submittedAt: daysAgo(22),
		parentId: "3",
	},
	{
		id: "16",
		postId: "3",
		userId: "4",
		user: mockUsers[3],
		message:
			"@sarahj Thank you so much! About 40 hours total. Loved every minute of it! 🎨",
		submittedAt: daysAgo(22),
		parentId: "10",
	},
	{
		id: "17",
		postId: "3",
		userId: "2",
		user: mockUsers[1],
		message: "@emmar That dedication is inspiring! Worth every hour 👏",
		submittedAt: daysAgo(22),
		parentId: "16",
	},
	{
		id: "4",
		postId: "4",
		userId: "1",
		user: mockUsers[0],
		message:
			"Just watched the tutorial! Amazing content as always. Here's my attempt at the technique.",
		submittedAt: daysAgo(18),
	},
	{
		id: "5",
		postId: "4",
		userId: "3",
		user: mockUsers[2],
		message: "This tutorial helped me so much! Sharing with my team.",
		submittedAt: daysAgo(18),
	},
	{
		id: "11",
		postId: "4",
		userId: "2",
		user: mockUsers[1],
		message:
			"@alexchen Thanks for watching! Your attempt looks great, keep practicing! 🎨",
		submittedAt: daysAgo(18),
		parentId: "4",
	},
	{
		id: "18",
		postId: "4",
		userId: "1",
		user: mockUsers[0],
		message:
			"@sarahj Thanks so much! Really helps having detailed feedback 🙏",
		submittedAt: daysAgo(18),
		parentId: "11",
	},
	{
		id: "19",
		postId: "4",
		userId: "3",
		user: mockUsers[2],
		message:
			"@sarahj Can you share the UI kit link? My team would love to use it!",
		submittedAt: daysAgo(18),
		parentId: "5",
	},
	{
		id: "6",
		postId: "6",
		userId: "2",
		user: mockUsers[1],
		message: "Love this gaming setup! The RGB lighting is perfect.",
		submittedAt: daysAgo(17),
	},
	{
		id: "12",
		postId: "6",
		userId: "5",
		user: mockUsers[4],
		message:
			"@sarahj Thanks! Took me months to get the lighting just right. What's your setup like?",
		submittedAt: daysAgo(17),
		parentId: "6",
	},
	{
		id: "20",
		postId: "6",
		userId: "2",
		user: mockUsers[1],
		message:
			"@davidk I'm still using my old MacBook 😅 but I love the setup! Inspiring me to upgrade",
		submittedAt: daysAgo(17),
		parentId: "12",
	},
	{
		id: "21",
		postId: "1",
		userId: "3",
		user: mockUsers[2],
		message:
			"Jumping in here, I built something similar for a client. Happy to share lessons learned. @sarahj",
		submittedAt: daysAgo(19),
		parentId: "1",
	},
	{
		id: "22",
		postId: "1",
		userId: "2",
		user: mockUsers[1],
		message:
			"@alexchen That would be amazing. What did you use for auth and payments?",
		submittedAt: daysAgo(19),
		parentId: "21",
	},
	{
		id: "23",
		postId: "1",
		userId: "3",
		user: mockUsers[2],
		message:
			"@sarahj Auth was NextAuth and payments via Stripe. Keep it boring and stable 😄",
		submittedAt: daysAgo(19),
		parentId: "22",
	},
	{
		id: "24",
		postId: "3",
		userId: "5",
		user: mockUsers[4],
		message:
			"Cyberpunk vibe is crazy good. The lighting feels cinematic. @emmar",
		submittedAt: daysAgo(22),
		parentId: "3",
	},
	{
		id: "25",
		postId: "3",
		userId: "4",
		user: mockUsers[3],
		message:
			"@davidk Thank you! I'm experimenting with neon fog and grain for that film look.",
		submittedAt: daysAgo(22),
		parentId: "24",
	},
	{
		id: "26",
		postId: "4",
		userId: "5",
		user: mockUsers[4],
		message:
			"@alexchen That technique is clean. Would you do a follow up on layering textures?",
		submittedAt: daysAgo(18),
		parentId: "4",
	},
	{
		id: "27",
		postId: "4",
		userId: "1",
		user: mockUsers[0],
		message:
			"@davidk +1 to that. A quick breakdown of brushes and texture workflow would help a ton.",
		submittedAt: daysAgo(18),
		parentId: "26",
	},
	{
		id: "28",
		postId: "6",
		userId: "3",
		user: mockUsers[2],
		message:
			"This setup is giving streamer pro max vibes. Cable management is elite 😮",
		submittedAt: daysAgo(17),
		parentId: "6",
	},
	{
		id: "29",
		postId: "6",
		userId: "5",
		user: mockUsers[4],
		message:
			"@alexchen Appreciate it! Next upgrade is a better mic arm and maybe a second monitor.",
		submittedAt: daysAgo(17),
		parentId: "28",
	},
	{
		id: "30",
		postId: "6",
		userId: "2",
		user: mockUsers[1],
		message:
			"@davidk Second monitor is a game changer. Once you try it, you can't go back 😂",
		submittedAt: daysAgo(17),
		parentId: "29",
	},
	{
		id: "31",
		postId: "7",
		userId: "8",
		user: mockUsers[7],
		content:
			"I can donate design templates for the learning platform. Happy to help with branding.",
		submittedAt: daysAgo(9),
		likes: 6,
		burns: 0,
		replyCount: 1,
	},
	{
		id: "32",
		postId: "7",
		userId: "2",
		user: mockUsers[1],
		content:
			"I'm in! I can record a short Figma basics workshop for beginners.",
		submittedAt: daysAgo(8),
		likes: 9,
		burns: 1,
		replyCount: 0,
	},
	{
		id: "33",
		postId: "7",
		userId: "1",
		user: mockUsers[0],
		content:
			"Thank you for supporting this. I'll share the roadmap and what we need next.",
		submittedAt: daysAgo(8),
		parentId: "31",
	},
	{
		id: "34",
		postId: "8",
		userId: "6",
		user: mockUsers[5],
		message:
			"My pitch is for a low-cost tutoring marketplace for rural students. 60 seconds, all impact.",
		submittedAt: daysAgo(10),
		proofUrl: "https://youtu.be/tutor-pitch",
		likes: 12,
		burns: 2,
		replyCount: 2,
	},
	{
		id: "35",
		postId: "8",
		userId: "9",
		user: mockUsers[8],
		message:
			"I'm building a tool-sharing network for trade apprentices. Short demo included.",
		submittedAt: daysAgo(9),
		proofUrl: "https://youtu.be/tool-share",
		likes: 7,
		burns: 0,
		replyCount: 0,
	},
	{
		id: "36",
		postId: "9",
		userId: "7",
		user: mockUsers[6],
		content:
			"Rooting for you, Chioma. I've been there. Sending a small contribution now.",
		submittedAt: daysAgo(5),
		likes: 4,
		replyCount: 0,
	},
	{
		id: "37",
		postId: "9",
		userId: "10",
		user: mockUsers[9],
		content:
			"Sharing this with my followers. You'll make it through final year! 🎓",
		submittedAt: daysAgo(4),
		likes: 10,
		replyCount: 1,
	},
	{
		id: "38",
		postId: "10",
		userId: "6",
		user: mockUsers[5],
		message:
			"Student ID attached. I'll use the data for online classes and coding practice.",
		submittedAt: daysAgo(3),
		proof: {
			type: "image",
			url: "/proof/student-id.jpg",
		},
		likes: 5,
		burns: 0,
		replyCount: 0,
	},
	{
		id: "39",
		postId: "10",
		userId: "9",
		user: mockUsers[8],
		message:
			"I'm preparing for my final project and need more access to tutorials.",
		submittedAt: daysAgo(3),
		proof: {
			type: "image",
			url: "/proof/student-id-2.jpg",
		},
		likes: 3,
		burns: 0,
		replyCount: 0,
	},
	{
		id: "40",
		postId: "10",
		userId: "2",
		user: mockUsers[1],
		message:
			"Supporting this. Students deserve access to tools that help them learn.",
		submittedAt: daysAgo(2),
		likes: 8,
		replyCount: 0,
	},
	{
		id: "41",
		postId: "11",
		userId: "8",
		user: mockUsers[7],
		content:
			"I can help source discounted tools. Let me know what you need most.",
		submittedAt: daysAgo(6),
		likes: 2,
		replyCount: 0,
	},
	{
		id: "42",
		postId: "11",
		userId: "7",
		user: mockUsers[6],
		content:
			"I have a contact who can get welding gloves and goggles at a lower cost.",
		submittedAt: daysAgo(6),
		likes: 4,
		replyCount: 0,
	},
	{
		id: "43",
		postId: "12",
		userId: "4",
		user: mockUsers[3],
		message:
			"My books this term cost more than usual. Any support helps a lot.",
		submittedAt: daysAgo(7),
		proofUrl: "https://drive.google.com/textbook-receipts",
		likes: 5,
		burns: 0,
		replyCount: 0,
	},
	{
		id: "44",
		postId: "12",
		userId: "6",
		user: mockUsers[5],
		message:
			"Sharing my study schedule and receipts. Thank you for supporting students!",
		submittedAt: daysAgo(7),
		proofUrl: "https://drive.google.com/student-schedule",
		likes: 2,
		replyCount: 0,
	},
	{
		id: "45",
		postId: "12",
		userId: "1",
		user: mockUsers[0],
		message:
			"I'll match the next two contributions to get this funded faster.",
		submittedAt: daysAgo(6),
		likes: 11,
		replyCount: 1,
	},
	{
		id: "46",
		postId: "13",
		userId: "3",
		user: mockUsers[2],
		content:
			"I can contribute a few hours of mentorship and review your budgets.",
		submittedAt: daysAgo(5),
		likes: 3,
		replyCount: 0,
	},
	{
		id: "47",
		postId: "13",
		userId: "5",
		user: mockUsers[4],
		content: "Sent a small amount. Keep going, the community is behind you.",
		submittedAt: daysAgo(5),
		likes: 4,
		replyCount: 0,
	},
	{
		id: "48",
		postId: "14",
		userId: "2",
		user: mockUsers[1],
		message:
			"My portfolio link is here. I'd love feedback on typography and layout.",
		submittedAt: daysAgo(4),
		proof: {
			type: "link",
			url: "https://dribbble.com/sarahj/portfolio",
		},
		likes: 6,
		replyCount: 1,
	},
	{
		id: "49",
		postId: "14",
		userId: "10",
		user: mockUsers[9],
		message:
			"I'm applying for my first product design role. Any feedback helps!",
		submittedAt: daysAgo(4),
		proof: {
			type: "link",
			url: "https://behance.net/blessing_e/portfolio",
		},
		likes: 5,
		replyCount: 0,
	},
	{
		id: "50",
		postId: "15",
		userId: "1",
		user: mockUsers[0],
		content:
			"Sharing my checklist from a previous move. Happy to send more tips.",
		submittedAt: daysAgo(12),
		likes: 7,
		replyCount: 0,
	},
	{
		id: "51",
		postId: "16",
		userId: "5",
		user: mockUsers[4],
		message:
			"I have extra peripherals if the giveaway goes ahead. Keep me posted!",
		submittedAt: daysAgo(11),
		likes: 2,
		replyCount: 0,
	},
	{
		id: "52",
		postId: "17",
		userId: "8",
		user: mockUsers[7],
		message:
			"Here's my 60-second pitch video. Building a sustainable fashion exchange.",
		submittedAt: daysAgo(3),
		proofUrl: "https://youtu.be/fashion-exchange",
		likes: 9,
		burns: 1,
		replyCount: 0,
	},
];

// Mock replies to entries.
export const mockReplies: Reply[] = [
	{
		id: "reply-1",
		parentId: "31",
		parentType: "entry",
		userId: "1",
		user: mockUsers[0],
		content: "Love this. I'll loop you in on the roadmap docs tonight.",
		createdAt: hoursAgo(14),
		likes: 4,
		burnCount: 0,
	},
	{
		id: "reply-2",
		parentId: "34",
		parentType: "entry",
		userId: "3",
		user: mockUsers[2],
		content: "This pitch is strong. I'd like to review your unit economics.",
		createdAt: hoursAgo(20),
		likes: 6,
		burnCount: 1,
	},
	{
		id: "reply-3",
		parentId: "34",
		parentType: "entry",
		userId: "2",
		user: mockUsers[1],
		content: "The impact angle is clear. Great job keeping it concise.",
		createdAt: hoursAgo(18),
		likes: 3,
		burnCount: 0,
	},
	{
		id: "reply-4",
		parentId: "37",
		parentType: "entry",
		userId: "6",
		user: mockUsers[5],
		content: "Thank you for boosting this. It means a lot.",
		createdAt: hoursAgo(10),
		likes: 2,
		burnCount: 0,
	},
	{
		id: "reply-5",
		parentId: "45",
		parentType: "entry",
		userId: "4",
		user: mockUsers[3],
		content: "Wow, that's incredibly generous. Thank you!",
		createdAt: hoursAgo(9),
		likes: 5,
		burnCount: 0,
	},
	{
		id: "reply-6",
		parentId: "48",
		parentType: "entry",
		userId: "3",
		user: mockUsers[2],
		content: "Strong work. I'd tighten the hero copy and add case studies.",
		createdAt: hoursAgo(12),
		likes: 4,
		burnCount: 0,
	},
	{
		id: "reply-7",
		parentId: "48",
		parentType: "entry",
		userId: "2",
		user: mockUsers[1],
		content:
			"Your color system is clean. Consider more contrast for headings.",
		createdAt: hoursAgo(11),
		likes: 3,
		burnCount: 0,
	},
	{
		id: "reply-8",
		parentId: "52",
		parentType: "entry",
		userId: "1",
		user: mockUsers[0],
		content: "Loved this idea. Could you share your traction metrics?",
		createdAt: hoursAgo(7),
		likes: 5,
		burnCount: 1,
	},
];

// Mock contributions for help requests.
export const mockContributions: HelpContribution[] = [
	{
		id: "1",
		postId: "2",
		userId: "1",
		user: mockUsers[0],
		amount: 100,
		currency: "USDC",
		message: "Keep learning and building! You've got this! 💪",
		contributedAt: daysAgo(22),
	},
	{
		id: "7",
		postId: "2",
		userId: "4",
		user: mockUsers[3],
		amount: 0,
		currency: "USDC",
		message: "@alexchen Thank you so much! This means everything to me 🙏",
		contributedAt: daysAgo(22),
		parentId: "1",
	},
	{
		id: "2",
		postId: "2",
		userId: "3",
		user: mockUsers[2],
		amount: 75,
		currency: "USDC",
		message: "Education is the best investment. Good luck with your studies!",
		contributedAt: daysAgo(21),
	},
	{
		id: "3",
		postId: "2",
		userId: "5",
		user: mockUsers[4],
		amount: 50,
		currency: "USDC",
		message: "Every developer needs good tools. Hope this helps!",
		contributedAt: daysAgo(21),
	},
	{
		id: "8",
		postId: "2",
		userId: "4",
		user: mockUsers[3],
		amount: 0,
		currency: "USDC",
		message:
			"@davidk Already looking at some great laptops with these funds 💻",
		contributedAt: daysAgo(21),
		parentId: "3",
	},
	{
		id: "4",
		postId: "2",
		userId: "2",
		user: mockUsers[1],
		amount: 20,
		currency: "USDC",
		message: "Small contribution but big support! 🎨",
		contributedAt: daysAgo(20),
	},
	{
		id: "5",
		postId: "5",
		userId: "1",
		user: mockUsers[0],
		amount: 200,
		currency: "USDC",
		message: "Mental health is so important. Take care of yourself!",
		contributedAt: daysAgo(19),
	},
	{
		id: "6",
		postId: "5",
		userId: "3",
		user: mockUsers[2],
		amount: 150,
		currency: "USDC",
		message: "Therapy changed my life. Hope this helps you too.",
		contributedAt: daysAgo(19),
	},
	{
		id: "9",
		postId: "5",
		userId: "5",
		user: mockUsers[4],
		amount: 0,
		currency: "USDC",
		message:
			"@marcusw That's so encouraging to hear. I'm hopeful this will help me too ❤️",
		contributedAt: daysAgo(19),
		parentId: "6",
	},
	{
		id: "10",
		postId: "7",
		userId: "8",
		user: mockUsers[7],
		amount: 120,
		currency: "USDC",
		message: "Covering hosting for a month. Keep the momentum going!",
		contributedAt: daysAgo(9),
	},
	{
		id: "11",
		postId: "7",
		userId: "2",
		user: mockUsers[1],
		amount: 60,
		currency: "USDC",
		message: "Happy to support free education resources.",
		contributedAt: daysAgo(8),
	},
	{
		id: "12",
		postId: "9",
		userId: "7",
		user: mockUsers[6],
		amount: 15000,
		currency: "NGN",
		message: "Sending a small amount for school fees.",
		contributedAt: daysAgo(5),
	},
	{
		id: "13",
		postId: "11",
		userId: "8",
		user: mockUsers[7],
		amount: 12000,
		currency: "NGN",
		message: "Hope this helps you get the first set of tools.",
		contributedAt: daysAgo(6),
	},
	{
		id: "14",
		postId: "13",
		userId: "5",
		user: mockUsers[4],
		amount: 90,
		currency: "USDC",
		message: "Pitch practice is tough. You've got this!",
		contributedAt: daysAgo(5),
	},
	{
		id: "15",
		postId: "15",
		userId: "1",
		user: mockUsers[0],
		amount: 300,
		currency: "USDC",
		message: "Happy to help with the deposit. Stay steady!",
		contributedAt: daysAgo(12),
	},
];

// Mock comments on posts.
export const mockComments: Comment[] = [
	{
		id: "1",
		postId: "1",
		userId: "2",
		user: mockUsers[1],
		content: "This is amazing! Thanks for supporting new developers 🙏",
		createdAt: daysAgo(21),
		parentId: undefined,
	},
	{
		id: "2",
		postId: "1",
		userId: "4",
		user: mockUsers[3],
		content: "Just entered! This community is so supportive ❤️",
		createdAt: daysAgo(21),
		parentId: undefined,
	},
	{
		id: "3",
		postId: "1",
		userId: "1",
		user: mockUsers[0],
		content: "Love seeing everyone's coding journeys! Keep building! 🚀",
		createdAt: daysAgo(21),
		parentId: "2",
	},
	{
		id: "4",
		postId: "2",
		userId: "3",
		user: mockUsers[2],
		content:
			"Just contributed! Education should be accessible to everyone 📚",
		createdAt: daysAgo(22),
		parentId: undefined,
	},
	{
		id: "5",
		postId: "3",
		userId: "5",
		user: mockUsers[4],
		content: "These NFTs look incredible! The art style is so unique 🎨",
		createdAt: daysAgo(23),
		parentId: undefined,
	},
];

// Mock activity feed items.
export const mockActivities: Activity[] = [
	{
		id: "1",
		userId: "1",
		type: "post_created",
		description: "created a new giveaway",
		postId: "1",
		createdAt: daysAgo(21),
	},
	{
		id: "2",
		userId: "2",
		type: "entry_submitted",
		description: "entered a giveaway",
		postId: "1",
		createdAt: daysAgo(20),
	},
	{
		id: "3",
		userId: "1",
		type: "contribution_made",
		description: "contributed to a help request",
		postId: "2",
		amount: 100,
		createdAt: daysAgo(22),
	},
	{
		id: "4",
		userId: "3",
		type: "post_created",
		description: "created a new giveaway",
		postId: "3",
		createdAt: daysAgo(23),
	},
	{
		id: "5",
		userId: "4",
		type: "post_created",
		description: "created a help request",
		postId: "2",
		createdAt: daysAgo(22),
	},
	{
		id: "6",
		userId: "8",
		type: "entry_submitted",
		description: "submitted a learning resources entry",
		postId: "7",
		createdAt: daysAgo(9),
	},
	{
		id: "7",
		userId: "2",
		type: "entry_submitted",
		description: "submitted a portfolio for review",
		postId: "14",
		createdAt: daysAgo(4),
	},
];

// Mock interactions across entries, replies, and posts.
export const mockLikes: Like[] = [
	{
		id: "like-1",
		userId: "1",
		targetId: "34",
		targetType: "entry",
		createdAt: hoursAgo(20),
	},
	{
		id: "like-2",
		userId: "2",
		targetId: "reply-2",
		targetType: "reply",
		createdAt: hoursAgo(19),
	},
	{
		id: "like-3",
		userId: "3",
		targetId: "31",
		targetType: "entry",
		createdAt: hoursAgo(15),
	},
	{
		id: "like-4",
		userId: "5",
		targetId: "48",
		targetType: "entry",
		createdAt: hoursAgo(12),
	},
	{
		id: "like-5",
		userId: "8",
		targetId: "reply-5",
		targetType: "reply",
		createdAt: hoursAgo(9),
	},
];

export const mockBurns: Burn[] = [
	{
		id: "burn-1",
		userId: "3",
		entryId: "34",
		createdAt: hoursAgo(18),
	},
	{
		id: "burn-2",
		userId: "1",
		entryId: "52",
		createdAt: hoursAgo(7),
	},
	{
		id: "burn-3",
		userId: "2",
		entryId: "31",
		createdAt: hoursAgo(14),
	},
];

export const mockShares: Share[] = [
	{
		id: "share-1",
		userId: "2",
		postId: "1",
		method: "twitter",
		createdAt: daysAgo(20),
	},
	{
		id: "share-2",
		userId: "7",
		postId: "9",
		method: "telegram",
		createdAt: daysAgo(4),
	},
	{
		id: "share-3",
		userId: "8",
		postId: "14",
		method: "link",
		createdAt: daysAgo(4),
	},
	{
		id: "share-4",
		userId: "1",
		postId: "15",
		method: "twitter",
		createdAt: daysAgo(12),
	},
];

// Mock posts: add new posts with unique IDs and matching relationships.
export const mockPosts: Post[] = [
	{
		id: "1",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "1",
		author: mockUsers[0],
		title: "🎁 $500 USDC Giveaway for New Developers!",
		description:
			"Celebrating our community growth! I'm giving away $500 USDC to help new developers get started. Share your coding journey and what you're building!",
		media: [
			{
				id: "1",
				type: "image",
				url: "/crypto-giveaway-banner.png",
			},
		],
		requirements: { proofRequired: false },
		selectionMethod: SelectionMethod.Random,
		createdAt: daysAgo(21),
		updatedAt: daysAgo(21),
		endsAt: daysFromNow(5),
		status: PostStatus.Open,
		burnCount: 234,
		shareCount: 89,
		commentCount: 45,
		prizeAmount: 500,
		currency: "USDC",
		winnerCount: 1,
		likesCount: 100,
		entriesCount: 11,
		selectionType: "random",
		entryRequirements: [
			"Follow @alexchen",
			"Share your coding story",
			"Tag 2 friends",
		],
		proofRequired: false,
		endDate: daysFromNow(5),
		entries: mockEntries.filter((e) => e.postId === "1"),
		winners: [],
	},
	{
		id: "2",
		category: PostCategory.HelpRequest,
		type: "help-request",
		authorId: "4",
		author: mockUsers[3],
		title: "🙏 Help Me Get a New Laptop for Coding",
		description:
			"Hi everyone! I'm a computer science student and my old laptop finally gave up. I need help raising funds for a new one to continue my studies and coding projects. Any contribution would mean the world to me!",
		createdAt: daysAgo(22),
		updatedAt: daysAgo(22),
		status: PostStatus.Open,
		burnCount: 156,
		shareCount: 67,
		commentCount: 23,
		targetAmount: 800,
		currentAmount: 245,
		currency: "USDC",
		likesCount: 44,
		entriesCount: 0,
		contributions: mockContributions.filter((c) => c.postId === "2"),
	},
	{
		id: "3",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "3",
		author: mockUsers[2],
		title: "🚀 NFT Collection Giveaway - 3 Winners!",
		description:
			'Launching my new NFT collection and want to give back to the community! Giving away 3 exclusive NFTs from the "Future Builders" collection.',
		media: [
			{
				id: "2",
				type: "image",
				url: "/futuristic-nft-collection.png",
			},
		],
		requirements: { proofRequired: true, minBadgeTier: BadgeTier.Silver },
		selectionMethod: SelectionMethod.MeritBased,
		createdAt: daysAgo(23),
		updatedAt: daysAgo(23),
		endsAt: daysFromNow(1),
		status: PostStatus.InProgress,
		burnCount: 445,
		shareCount: 178,
		commentCount: 92,
		prizeAmount: 3,
		currency: "NFT",
		winnerCount: 3,
		likesCount: 64,
		entriesCount: 6,
		selectionType: "manual",
		entryRequirements: [
			"Follow @marcusw",
			"Repost this giveaway",
			"Show your creative work",
		],
		proofRequired: true,
		endDate: daysFromNow(1),
		entries: mockEntries.filter((e) => e.postId === "3"),
		winners: [],
	},
	{
		id: "4",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "2",
		author: mockUsers[1],
		title: "🎨 Design Tutorial Video + Free Resources",
		description:
			"Just dropped my latest design tutorial! Learn advanced Figma techniques and get access to my premium design system. Giving away 5 copies of my complete UI kit to lucky winners!",
		media: [
			{
				id: "3",
				type: "video",
				url: "/design-tutorial-thumbnail.png",
				thumbnail: "/figma-tutorial-thumbnail.png",
			},
		],
		requirements: { proofRequired: false },
		selectionMethod: SelectionMethod.Random,
		createdAt: daysAgo(18),
		updatedAt: daysAgo(18),
		endsAt: daysFromNow(4),
		status: PostStatus.Open,
		burnCount: 89,
		shareCount: 34,
		commentCount: 18,
		prizeAmount: 5,
		currency: "Digital Assets",
		winnerCount: 5,
		likesCount: 76,
		entriesCount: 7,
		selectionType: "random",
		entryRequirements: [
			"Watch the full video",
			"Follow @sarahj",
			"Share your design work",
		],
		proofRequired: false,
		endDate: daysFromNow(4),
		entries: mockEntries.filter((e) => e.postId === "4"),
		winners: [],
	},
	{
		id: "5",
		category: PostCategory.HelpRequest,
		type: "help-request",
		authorId: "5",
		author: mockUsers[4],
		title: "💚 Mental Health Support - Therapy Sessions",
		description:
			"Hey community, I've been struggling with anxiety and depression lately. I found a great therapist but the sessions are expensive. Any help would be incredibly appreciated. Mental health matters!",
		createdAt: daysAgo(19),
		updatedAt: daysAgo(19),
		status: PostStatus.Open,
		burnCount: 67,
		shareCount: 23,
		commentCount: 15,
		targetAmount: 600,
		currentAmount: 350,
		currency: "USDC",
		likesCount: 59,
		entriesCount: 0,
		contributions: mockContributions.filter((c) => c.postId === "5"),
	},
	{
		id: "6",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "5",
		author: mockUsers[4],
		title: "🎮 Ultimate Gaming Setup Showcase + Giveaway",
		description:
			"Finally completed my dream gaming setup! Check out the full tour and enter to win some awesome gaming peripherals. Multiple winners, multiple prizes!",
		media: [
			{
				id: "4",
				type: "image",
				url: "/rgb-gaming-setup.png",
			},
			{
				id: "5",
				type: "image",
				url: "/mechanical-keyboard-and-gaming-mouse.png",
			},
			{
				id: "6",
				type: "video",
				url: "/gaming-setup-tour.png",
				thumbnail: "/placeholder-whvi9.png",
			},
			{
				id: "7",
				type: "image",
				url: "/placeholder-8awlp.png",
			},
		],
		requirements: { proofRequired: false },
		selectionMethod: SelectionMethod.Random,
		createdAt: daysAgo(17),
		updatedAt: daysAgo(17),
		endsAt: daysFromNow(7),
		status: PostStatus.Open,
		burnCount: 156,
		shareCount: 78,
		commentCount: 42,
		prizeAmount: 4,
		currency: "Gaming Gear",
		winnerCount: 4,
		likesCount: 90,
		entriesCount: 6,
		selectionType: "random",
		entryRequirements: [
			"Follow @davidk",
			"Share your gaming setup",
			"Tag a gaming buddy",
		],
		proofRequired: false,
		endDate: daysFromNow(7),
		entries: mockEntries.filter((e) => e.postId === "6"),
		winners: [],
	},
	{
		id: "7",
		category: PostCategory.HelpRequest,
		type: "help-request",
		authorId: "1",
		author: mockUsers[0],
		title: "📚 Community Learning Resources Fund",
		description:
			"Building a free learning platform for underserved communities. We need funds for hosting, content creation, and educational materials. Every dollar helps someone learn to code!",
		media: [
			{
				id: "8",
				type: "image",
				url: "/placeholder-r9nsr.png",
			},
			{
				id: "9",
				type: "image",
				url: "/coding-bootcamp-classroom.png",
			},
		],
		createdAt: daysAgo(24),
		updatedAt: daysAgo(24),
		status: PostStatus.Open,
		burnCount: 298,
		shareCount: 145,
		commentCount: 67,
		targetAmount: 2000,
		currentAmount: 1450,
		currency: "USDC",
		likesCount: 87,
		entriesCount: 3,
		contributions: mockContributions.filter((c) => c.postId === "7"),
	},
	{
		id: "8",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "3",
		author: mockUsers[2],
		title: "💡 Startup Pitch Competition - Win Mentorship!",
		description:
			"Calling all entrepreneurs! Pitch your startup idea in 60 seconds or less. Winners get 1-on-1 mentorship sessions with successful founders, plus funding opportunities. Let's build the future together!",
		requirements: { proofRequired: true, minReputation: 200 },
		selectionMethod: SelectionMethod.MeritBased,
		createdAt: daysAgo(25),
		updatedAt: daysAgo(25),
		endsAt: daysFromNow(10),
		status: PostStatus.InProgress,
		burnCount: 189,
		shareCount: 92,
		commentCount: 38,
		prizeAmount: 3,
		currency: "Mentorship Sessions",
		winnerCount: 3,
		likesCount: 71,
		entriesCount: 2,
		selectionType: "manual",
		entryRequirements: [
			"Submit 60-second pitch video",
			"Follow @marcusw",
			"Use hashtag #StartupPitch2024",
		],
		proofRequired: true,
		endDate: daysFromNow(10),
		entries: mockEntries.filter((e) => e.postId === "8"),
		winners: [],
	},
	{
		id: "9",
		category: PostCategory.HelpRequest,
		type: "help-request",
		authorId: "6",
		author: mockUsers[5],
		title: "🎓 Help Me Pay School Fees - Final Year",
		description:
			"I'm in my final year at UNIPORT studying Computer Science. My family is struggling to raise the ₦180,000 for this semester's fees. Any help would mean I can graduate and start working to support them.",
		createdAt: daysAgo(5),
		updatedAt: daysAgo(5),
		status: PostStatus.Open,
		burnCount: 78,
		shareCount: 34,
		commentCount: 18,
		targetAmount: 180000,
		currentAmount: 85000,
		currency: "NGN",
		likesCount: 56,
		entriesCount: 2,
		contributions: mockContributions.filter((c) => c.postId === "9"),
	},
	{
		id: "10",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "7",
		author: mockUsers[6],
		title: "📱 5GB Data Giveaway for Students!",
		description:
			"Running my business has been good to me. Want to help 10 students with free data for the month. Just show your student ID and tell me how you'll use it for learning!",
		requirements: { proofRequired: true },
		selectionMethod: SelectionMethod.Random,
		createdAt: daysAgo(3),
		updatedAt: daysAgo(3),
		endsAt: daysFromNow(2),
		status: PostStatus.Open,
		burnCount: 145,
		shareCount: 92,
		commentCount: 38,
		prizeAmount: 10,
		currency: "Data Bundle",
		winnerCount: 10,
		likesCount: 88,
		entriesCount: 3,
		selectionType: "random",
		entryRequirements: [
			"Show student ID",
			"Explain how you'll use it",
			"Follow @tbakare",
		],
		proofRequired: true,
		endDate: daysFromNow(2),
		entries: mockEntries.filter((e) => e.postId === "10"),
		winners: [],
	},
	{
		id: "11",
		category: PostCategory.HelpRequest,
		type: "help-request",
		authorId: "9",
		author: mockUsers[8],
		title: "💼 Need Help Getting Tools for My Trade",
		description:
			"I'm learning welding to support my family. Need ₦50,000 to buy basic tools so I can start taking small jobs. Already have training, just need equipment.",
		createdAt: daysAgo(6),
		updatedAt: daysAgo(6),
		status: PostStatus.Open,
		burnCount: 92,
		shareCount: 41,
		commentCount: 22,
		targetAmount: 50000,
		currentAmount: 28000,
		currency: "NGN",
		likesCount: 48,
		entriesCount: 2,
		contributions: mockContributions.filter((c) => c.postId === "11"),
	},
	{
		id: "12",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "1",
		author: mockUsers[0],
		title: "📘 Textbook Support for Students",
		description:
			"I'm covering textbook costs for three students this month. Share what you're studying and why these books will help you finish the semester strong.",
		requirements: { proofRequired: true, minBadgeTier: BadgeTier.Bronze },
		selectionMethod: SelectionMethod.FirstCome,
		createdAt: daysAgo(8),
		updatedAt: daysAgo(8),
		endsAt: daysFromNow(3),
		status: PostStatus.Open,
		burnCount: 62,
		shareCount: 19,
		commentCount: 11,
		prizeAmount: 200,
		currency: "USDC",
		maxWinners: 3,
		currentWinners: 0,
		likesCount: 43,
		entriesCount: 3,
		selectionType: "first-come",
		entryRequirements: [
			"Share your course list",
			"Upload receipts",
			"Follow @alexchen",
		],
		proofRequired: true,
		endDate: daysFromNow(3),
		entries: mockEntries.filter((e) => e.postId === "12"),
		winners: [],
	},
	{
		id: "13",
		category: PostCategory.HelpRequest,
		type: "help-request",
		authorId: "6",
		author: mockUsers[5],
		title: "🧠 Help Fund My Certification Exam",
		description:
			"I'm preparing for my cloud certification and the exam fee is high. Any support helps me level up my skills and land better roles.",
		createdAt: daysAgo(6),
		updatedAt: daysAgo(6),
		status: PostStatus.InProgress,
		burnCount: 41,
		shareCount: 15,
		commentCount: 7,
		targetAmount: 350,
		currentAmount: 190,
		currency: "USDC",
		likesCount: 26,
		entriesCount: 2,
		contributions: mockContributions.filter((c) => c.postId === "13"),
	},
	{
		id: "14",
		category: PostCategory.SkillShare,
		type: "giveaway",
		authorId: "2",
		author: mockUsers[1],
		title: "📝 Portfolio Review Slots (Skill Share)",
		description:
			"Offering 6 portfolio review slots this week. Share your portfolio link and the role you're applying for. I'll give actionable feedback.",
		requirements: { proofRequired: true, minReputation: 50 },
		selectionMethod: SelectionMethod.FirstCome,
		createdAt: daysAgo(5),
		updatedAt: daysAgo(5),
		endsAt: daysFromNow(2),
		status: PostStatus.Open,
		burnCount: 22,
		shareCount: 14,
		commentCount: 9,
		prizeAmount: 6,
		currency: "Review Slots",
		maxWinners: 6,
		currentWinners: 0,
		likesCount: 35,
		entriesCount: 2,
		selectionType: "first-come",
		entryRequirements: [
			"Share portfolio link",
			"Mention target role",
			"Follow @sarahj",
		],
		proofRequired: true,
		endDate: daysFromNow(2),
		entries: mockEntries.filter((e) => e.postId === "14"),
		winners: [],
	},
	{
		id: "15",
		category: PostCategory.HelpRequest,
		type: "help-request",
		authorId: "8",
		author: mockUsers[7],
		title: "🏠 Help With a Short-Term Rent Gap",
		description:
			"I'm between client payments and need a short-term bridge to cover rent. I've attached my invoice schedule and can pay this forward.",
		createdAt: daysAgo(13),
		updatedAt: daysAgo(13),
		status: PostStatus.Completed,
		burnCount: 33,
		shareCount: 12,
		commentCount: 6,
		targetAmount: 300,
		currentAmount: 300,
		currency: "USDC",
		likesCount: 28,
		entriesCount: 1,
		contributions: mockContributions.filter((c) => c.postId === "15"),
	},
	{
		id: "16",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "5",
		author: mockUsers[4],
		title: "🎧 Audio Gear Giveaway (Cancelled)",
		description:
			"I was planning to give away audio gear, but shipping costs spiked. I'll reschedule soon with better logistics.",
		requirements: { proofRequired: false },
		selectionMethod: SelectionMethod.Random,
		createdAt: daysAgo(11),
		updatedAt: daysAgo(11),
		endsAt: daysFromNow(1),
		status: PostStatus.Cancelled,
		burnCount: 19,
		shareCount: 8,
		commentCount: 5,
		prizeAmount: 2,
		currency: "Audio Gear",
		winnerCount: 2,
		likesCount: 21,
		entriesCount: 1,
		selectionType: "random",
		entryRequirements: ["Share your setup", "Follow @davidk"],
		proofRequired: false,
		endDate: daysFromNow(1),
		entries: mockEntries.filter((e) => e.postId === "16"),
		winners: [],
	},
	{
		id: "17",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "3",
		author: mockUsers[2],
		title: "🚀 Founder Pitch Fridays",
		description:
			"Weekly pitch showcase. Submit a 60-second video and we'll feature the top founders across the community feed.",
		requirements: { proofRequired: true },
		selectionMethod: SelectionMethod.MeritBased,
		createdAt: daysAgo(4),
		updatedAt: daysAgo(4),
		endsAt: daysFromNow(4),
		status: PostStatus.Open,
		burnCount: 40,
		shareCount: 16,
		commentCount: 10,
		prizeAmount: 3,
		currency: "Mentorship",
		winnerCount: 3,
		likesCount: 30,
		entriesCount: 1,
		selectionType: "manual",
		entryRequirements: ["Submit a pitch video", "Tag your cofounder"],
		proofRequired: true,
		endDate: daysFromNow(4),
		entries: mockEntries.filter((e) => e.postId === "17"),
		winners: [],
	},
	{
		id: "18",
		category: PostCategory.HelpRequest,
		type: "help-request",
		authorId: "9",
		author: mockUsers[8],
		title: "🚲 Help Me Replace My Delivery Bike",
		description:
			"My delivery bike broke down, which is my main source of income. I need help fixing or replacing it so I can get back to work.",
		createdAt: daysAgo(2),
		updatedAt: daysAgo(2),
		status: PostStatus.Completed,
		burnCount: 28,
		shareCount: 9,
		commentCount: 4,
		targetAmount: 200,
		currentAmount: 200,
		currency: "USDC",
		likesCount: 19,
		entriesCount: 0,
		contributions: [],
	},
	{
		id: "19",
		category: PostCategory.Giveaway,
		type: "giveaway",
		authorId: "7",
		author: mockUsers[6],
		title: "📦 Care Package Giveaway",
		description:
			"I put together 5 care packages with groceries and essentials. Applications are paused while I finalize logistics.",
		requirements: { proofRequired: false },
		selectionMethod: SelectionMethod.Random,
		createdAt: daysAgo(2),
		updatedAt: daysAgo(2),
		endsAt: daysFromNow(5),
		status: PostStatus.Cancelled,
		burnCount: 17,
		shareCount: 6,
		commentCount: 3,
		prizeAmount: 5,
		currency: "Care Packages",
		winnerCount: 5,
		likesCount: 14,
		entriesCount: 0,
		selectionType: "random",
		entryRequirements: ["Share your story"],
		proofRequired: false,
		endDate: daysFromNow(5),
		entries: [],
		winners: [],
	},
	{
		id: "20",
		category: PostCategory.HelpRequest,
		type: "help-request",
		authorId: "10",
		author: mockUsers[9],
		title: "💻 Raise Funds for a Used Laptop",
		description:
			"I'm switching to product design and need a used laptop to run Figma and Adobe tools. Any help gets me closer.",
		createdAt: daysAgo(1),
		updatedAt: daysAgo(1),
		status: PostStatus.InProgress,
		burnCount: 22,
		shareCount: 7,
		commentCount: 5,
		targetAmount: 500,
		currentAmount: 180,
		currency: "USDC",
		likesCount: 17,
		entriesCount: 0,
		contributions: [],
	},
	{
		id: "21",
		category: PostCategory.SkillShare,
		type: "giveaway",
		authorId: "1",
		author: mockUsers[0],
		title: "📚 Study Sprint Accountability (Skill Share)",
		description:
			"Running a 2-week study sprint with daily check-ins. Join if you want structure, peer accountability, and weekly office hours.",
		requirements: { proofRequired: false },
		selectionMethod: SelectionMethod.FirstCome,
		createdAt: hoursAgo(12),
		updatedAt: hoursAgo(12),
		endsAt: daysFromNow(6),
		status: PostStatus.Open,
		burnCount: 11,
		shareCount: 5,
		commentCount: 2,
		prizeAmount: 20,
		currency: "Seats",
		maxWinners: 20,
		currentWinners: 4,
		likesCount: 12,
		entriesCount: 0,
		selectionType: "first-come",
		entryRequirements: ["Commit to daily check-ins"],
		proofRequired: false,
		endDate: daysFromNow(6),
		entries: [],
		winners: [],
	},
];

// Helper function to get user by ID.
export function getUserById(id: string): User | undefined {
	return mockUsers.find((user) => user.id === id);
}

// Helper function to get posts by creator.
export function getPostsByCreator(creatorId: string): Post[] {
	return mockPosts.filter((post) => post.authorId === creatorId);
}

// Helper function to get entries by post.
export function getEntriesByPost(postId: string): Entry[] {
	return mockEntries.filter((entry) => entry.postId === postId);
}

// Helper function to get replies by entry.
export function getRepliesByEntry(entryId: string): Reply[] {
	return mockReplies.filter((reply) => reply.parentId === entryId);
}

// Helper function to get contributions by post.
export function getContributionsByPost(postId: string): HelpContribution[] {
	return mockContributions.filter((c) => c.postId === postId);
}
